Attribute VB_Name = "MULTILANE_HIGHWAY_SPECIAL_GRADE"
''''''''''''''''''''''''''''''''''
'MULTILANE HIGHWAY_SPECIFIC GRADE'
''''''''''''''''''''''''''''''''''

'Run all
'=======

Sub RUN_MULTILANE_SG()
    Call ET_UP_SG
    Call ER_UP_SG
    Call ET_DOWN_SG
End Sub


Private Sub ET_UP_SG()
    Call FOURD_INTERPOLATION([MULTILANE_HIGHWAY_SPECIAL_GRADE[Grade '[%']]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Extensão]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Pt]], "21-9_ET_UP", [MULTILANE_HIGHWAY_SPECIAL_GRADE[ET_UP]])
End Sub
    
Private Sub ER_UP_SG()
    Call FOURD_INTERPOLATION([MULTILANE_HIGHWAY_SPECIAL_GRADE[Grade '[%']]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Extensão]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Pt]], "21-10_ER_Up", [MULTILANE_HIGHWAY_SPECIAL_GRADE[ER_UP]])
End Sub

Private Sub ET_DOWN_SG()
    Call FOURD_INTERPOLATION([MULTILANE_HIGHWAY_SPECIAL_GRADE[Grade '[%']]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Extensão]], [MULTILANE_HIGHWAY_SPECIAL_GRADE[Pt]], "21-11_ET_Down", [MULTILANE_HIGHWAY_SPECIAL_GRADE[ET_DOWN]])
End Sub
